import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const base='http://localhost:8100';
const credentials=await readFile(new URL('data/admin-credentials.txt',import.meta.url),'utf8');
const password=credentials.match(/^Password: (.+)$/m)[1];
const call=(path,options={})=>fetch(base+path,{redirect:'manual',...options});
assert.equal((await call('/')).status,200);
assert.equal((await call('/workspace')).status,303);
assert.equal((await call('/api/workspace')).status,401);
assert.equal((await call('/app.js')).status,401);
assert.equal((await call('/data/admin.json')).status,404);
const headers={'Content-Type':'application/json',Origin:base};
assert.equal((await call('/api/login',{method:'POST',headers,body:JSON.stringify({username:'admin',password:'incorrect'})})).status,401);
const login=await call('/api/login',{method:'POST',headers,body:JSON.stringify({username:'admin',password})});
assert.equal(login.status,200);
const cookie=login.headers.get('set-cookie').split(';')[0];
assert.match(login.headers.get('set-cookie'),/HttpOnly/);
assert.match(login.headers.get('set-cookie'),/SameSite=Strict/);
const authHeaders={...headers,Cookie:cookie};
assert.equal((await call('/workspace',{headers:authHeaders})).status,200);
const session=await (await call('/api/session',{headers:authHeaders})).json();
const workspace=await (await call('/api/workspace',{headers:authHeaders})).json();
assert.equal((await call('/api/workspace',{method:'PUT',headers:authHeaders,body:JSON.stringify(workspace)})).status,403);
const writeHeaders={...authHeaders,'x-csrf-token':session.csrf};
assert.equal((await call('/api/workspace',{method:'PUT',headers:writeHeaders,body:'{"clients":[],"requests":[{}]}'})).status,422);
assert.equal((await call('/api/workspace',{method:'PUT',headers:{...writeHeaders,Origin:'https://unrelated.example'},body:JSON.stringify(workspace)})).status,403);
assert.equal((await call('/api/workspace',{method:'PUT',headers:writeHeaders,body:JSON.stringify(workspace)})).status,200);
assert.equal((await call('/api/logout',{method:'POST',headers:writeHeaders})).status,200);
assert.equal((await call('/api/workspace',{headers:authHeaders})).status,401);
console.log('Passed: public homepage, private routes, login rejection, admin login, secure cookie flags, CSRF, origin checks, validation, persistence, logout revocation.');
